/**
 * Shared type → ID category mappings and fixed enum options.
 * Used by both mc-completion.ts and mc-validation.ts.
 */

/** Map parameter types to knowledge-base ID categories */
export const TYPE_TO_CATEGORY: Record<string, string> = {
  Item: 'items',
  Block: 'blocks',
  EntityType: 'entities',
  Effect: 'effects',
  Enchantment: 'enchantments',
  Enchant: 'enchantments',
  Particle: 'particles',
  Sound: 'sounds',
  Biome: 'biomes',
  Fog: 'fog',
  Animation: 'animations',
  GameRule: 'gamerules',
  Structure: 'structures',
}

/** A fixed option with value and description */
export interface FixedOption {
  value: string
  description: string
}

/** Fixed options for enum-like parameter types (with descriptions) */
export const FIXED_OPTIONS: Record<string, FixedOption[]> = {
  target: [
    { value: '@p', description: '最近的玩家' },
    { value: '@a', description: '所有玩家' },
    { value: '@e', description: '所有实体' },
    { value: '@r', description: '随机玩家' },
    { value: '@s', description: '执行者自身' },
    { value: '@initiator', description: 'NPC交互发起者' },
  ],
  boolean: [
    { value: 'true', description: '是' },
    { value: 'false', description: '否' },
  ],
  Boolean: [
    { value: 'true', description: '是' },
    { value: 'false', description: '否' },
  ],
  gamemode: [
    { value: 'survival', description: '生存模式' },
    { value: 'creative', description: '创造模式' },
    { value: 'adventure', description: '冒险模式' },
    { value: 'spectator', description: '旁观模式' },
  ],
  GameMode: [
    { value: 'survival', description: '生存模式' },
    { value: 'creative', description: '创造模式' },
    { value: 'adventure', description: '冒险模式' },
    { value: 'spectator', description: '旁观模式' },
  ],
  difficulty: [
    { value: 'peaceful', description: '和平' },
    { value: 'easy', description: '简单' },
    { value: 'normal', description: '普通' },
    { value: 'hard', description: '困难' },
  ],
  Difficulty: [
    { value: 'peaceful', description: '和平' },
    { value: 'easy', description: '简单' },
    { value: 'normal', description: '普通' },
    { value: 'hard', description: '困难' },
  ],
  DamageCause: [
    { value: 'anvil', description: '铁砧砸落' },
    { value: 'block_explosion', description: '方块爆炸' },
    { value: 'charging', description: '冲撞' },
    { value: 'contact', description: '接触伤害(仙人掌等)' },
    { value: 'drowning', description: '溺水' },
    { value: 'entity_attack', description: '实体攻击' },
    { value: 'entity_explosion', description: '实体爆炸' },
    { value: 'fall', description: '摔落' },
    { value: 'falling_block', description: '下落方块' },
    { value: 'fire', description: '火焰' },
    { value: 'fire_tick', description: '着火' },
    { value: 'fireworks', description: '烟花' },
    { value: 'fly_into_wall', description: '撞墙(鞘翅)' },
    { value: 'freezing', description: '冰冻' },
    { value: 'lava', description: '岩浆' },
    { value: 'lightning', description: '雷击' },
    { value: 'magic', description: '魔法' },
    { value: 'magma', description: '岩浆块' },
    { value: 'none', description: '无' },
    { value: 'override', description: '覆盖' },
    { value: 'piston', description: '活塞' },
    { value: 'projectile', description: '弹射物' },
    { value: 'ram_attack', description: '山羊冲撞' },
    { value: 'self_destruct', description: '自毁' },
    { value: 'sonic_boom', description: '音波攻击' },
    { value: 'soul_campfire', description: '灵魂营火' },
    { value: 'stalactite', description: '钟乳石' },
    { value: 'stalagmite', description: '石笋' },
    { value: 'starve', description: '饥饿' },
    { value: 'suffocation', description: '窒息' },
    { value: 'temperature', description: '温度' },
    { value: 'thorns', description: '荆棘' },
    { value: 'void', description: '虚空' },
    { value: 'wither', description: '凋零' },
  ],
  MaskMode: [
    { value: 'masked', description: '仅复制非空气方块' },
    { value: 'filtered', description: '仅复制指定方块' },
    { value: 'replace', description: '复制所有方块' },
  ],
  CloneMode: [
    { value: 'force', description: '强制复制(允许重叠)' },
    { value: 'move', description: '移动(原位置变空气)' },
    { value: 'normal', description: '正常复制' },
  ],
  FillMode: [
    { value: 'destroy', description: '破坏原方块并替换' },
    { value: 'hollow', description: '仅填充外壳,内部空气' },
    { value: 'keep', description: '仅替换空气方块' },
    { value: 'outline', description: '仅外壳,不改内部' },
    { value: 'replace', description: '替换所有方块' },
  ],
  SetBlockMode: [
    { value: 'destroy', description: '破坏原方块并替换' },
    { value: 'keep', description: '仅替换空气方块' },
    { value: 'replace', description: '直接替换' },
  ],
  Ability: [
    { value: 'worldbuilder', description: '世界建造者' },
    { value: 'mayfly', description: '允许飞行' },
    { value: 'mute', description: '禁言' },
    { value: 'noclip', description: '穿墙' },
    { value: 'flyspeed', description: '飞行速度' },
    { value: 'walkspeed', description: '行走速度' },
    { value: 'instabuild', description: '瞬间破坏' },
    { value: 'lightning', description: '闪电' },
    { value: 'invulnerable', description: '无敌' },
    { value: 'mine', description: '挖掘' },
    { value: 'doorsandswitches', description: '使用门和开关' },
    { value: 'opencontainers', description: '打开容器' },
    { value: 'attackplayers', description: '攻击玩家' },
    { value: 'attackmobs', description: '攻击生物' },
    { value: 'operatorcommands', description: '使用管理员命令' },
    { value: 'teleport', description: '传送' },
    { value: 'build', description: '放置方块' },
  ],
  EaseType: [
    { value: 'linear', description: '线性' },
    { value: 'in_back', description: '回弹缓入' },
    { value: 'in_bounce', description: '弹跳缓入' },
    { value: 'in_circ', description: '圆形缓入' },
    { value: 'in_cubic', description: '三次方缓入' },
    { value: 'in_elastic', description: '弹性缓入' },
    { value: 'in_expo', description: '指数缓入' },
    { value: 'in_quad', description: '二次方缓入' },
    { value: 'in_quart', description: '四次方缓入' },
    { value: 'in_quint', description: '五次方缓入' },
    { value: 'in_sine', description: '正弦缓入' },
    { value: 'out_back', description: '回弹缓出' },
    { value: 'out_bounce', description: '弹跳缓出' },
    { value: 'out_circ', description: '圆形缓出' },
    { value: 'out_cubic', description: '三次方缓出' },
    { value: 'out_elastic', description: '弹性缓出' },
    { value: 'out_expo', description: '指数缓出' },
    { value: 'out_quad', description: '二次方缓出' },
    { value: 'out_quart', description: '四次方缓出' },
    { value: 'out_quint', description: '五次方缓出' },
    { value: 'out_sine', description: '正弦缓出' },
    { value: 'in_out_back', description: '回弹缓入缓出' },
    { value: 'in_out_bounce', description: '弹跳缓入缓出' },
    { value: 'in_out_circ', description: '圆形缓入缓出' },
    { value: 'in_out_cubic', description: '三次方缓入缓出' },
    { value: 'in_out_elastic', description: '弹性缓入缓出' },
    { value: 'in_out_expo', description: '指数缓入缓出' },
    { value: 'in_out_quad', description: '二次方缓入缓出' },
    { value: 'in_out_quart', description: '四次方缓入缓出' },
    { value: 'in_out_quint', description: '五次方缓入缓出' },
    { value: 'in_out_sine', description: '正弦缓入缓出' },
    { value: 'spring', description: '弹簧' },
  ],
  InputPermission: [
    { value: 'camera', description: '摄像机/视角控制' },
    { value: 'movement', description: '所有移动控制' },
    { value: 'lateral_movement', description: '横向移动控制' },
    { value: 'jump', description: '跳跃' },
    { value: 'sneak', description: '潜行' },
    { value: 'mount', description: '骑乘' },
    { value: 'dismount', description: '下坐骑' },
    { value: 'move_forward', description: '向前移动' },
    { value: 'move_backward', description: '向后移动' },
    { value: 'move_left', description: '向左移动' },
    { value: 'move_right', description: '向右移动' },
  ],
  HudElement: [
    { value: 'paperdoll', description: '角色纸娃娃' },
    { value: 'armor', description: '护甲栏' },
    { value: 'tooltips', description: '工具提示' },
    { value: 'touch_controls', description: '触控按钮' },
    { value: 'crosshair', description: '准心' },
    { value: 'hotbar', description: '快捷栏' },
    { value: 'health', description: '生命值' },
    { value: 'progress_bar', description: '进度条' },
    { value: 'food_bar', description: '饥饿值' },
    { value: 'air_bubbles', description: '氧气泡' },
    { value: 'horse_health', description: '马匹生命值' },
    { value: 'status_effects', description: '状态效果图标' },
    { value: 'item_text', description: '物品文本' },
    { value: 'all', description: '所有元素' },
  ],
  EntityEquipmentSlot: [
    { value: 'mainhand', description: '主手' },
    { value: 'offhand', description: '副手' },
    { value: 'head', description: '头部' },
    { value: 'chest', description: '胸部' },
    { value: 'legs', description: '腿部' },
    { value: 'feet', description: '脚部' },
    { value: 'slot.weapon.mainhand', description: '主手武器槽' },
    { value: 'slot.weapon.offhand', description: '副手武器槽' },
    { value: 'slot.armor.head', description: '头盔槽' },
    { value: 'slot.armor.chest', description: '胸甲槽' },
    { value: 'slot.armor.legs', description: '护腿槽' },
    { value: 'slot.armor.feet', description: '靴子槽' },
    { value: 'slot.hotbar', description: '快捷栏' },
    { value: 'slot.inventory', description: '物品栏' },
    { value: 'slot.enderchest', description: '末影箱' },
  ],
  CameraPreset: [
    { value: 'minecraft:first_person', description: '第一人称' },
    { value: 'minecraft:third_person', description: '第三人称(背面)' },
    { value: 'minecraft:third_person_front', description: '第三人称(正面)' },
    { value: 'minecraft:free', description: '自由视角' },
  ],
  MobEvent: [
    { value: 'minecraft:pillager_patrols_event', description: '掠夺者巡逻' },
    { value: 'minecraft:wandering_trader_event', description: '流浪商人生成' },
    { value: 'minecraft:ender_dragon_event', description: '末影龙事件' },
    { value: 'minecraft:events_enabled', description: '全部事件开关' },
  ],
  Dimension: [
    { value: 'overworld', description: '主世界' },
    { value: 'nether', description: '下界' },
    { value: 'the_end', description: '末地' },
  ],
  operator: [
    { value: '+=', description: '加法赋值' },
    { value: '-=', description: '减法赋值' },
    { value: '*=', description: '乘法赋值' },
    { value: '/=', description: '除法赋值' },
    { value: '%=', description: '取余赋值' },
    { value: '<', description: '取较小值' },
    { value: '>', description: '取较大值' },
    { value: '=', description: '直接赋值' },
    { value: '><', description: '交换值' },
  ],
}

/**
 * Get just the value strings for a fixed option type.
 * Used for validation where descriptions aren't needed.
 */
export function getFixedOptionValues(type: string): string[] | undefined {
  const opts = FIXED_OPTIONS[type]
  if (!opts) return undefined
  return opts.map((o) => o.value)
}
