"""Export project data as .mcfunction file content."""

from __future__ import annotations

from datetime import datetime
from typing import Any


def generate_mcfunction(project: dict[str, Any]) -> str:
    """Generate .mcfunction file content from a project result dict.

    Args:
        project: A dict matching ProjectResult schema (phases, tasks, command_blocks).

    Returns:
        The .mcfunction file content as a string.
    """
    lines: list[str] = []

    # Header
    project_name = project.get("project_name", "Untitled Project")
    lines.append(f"# {project_name}")
    lines.append(f"# Generated by Minecraft BE AI Commander")
    lines.append(f"# Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")

    overview = project.get("overview", "")
    if overview:
        lines.append(f"# {overview}")

    lines.append("")

    # Iterate phases and tasks
    for phase in project.get("phases", []):
        phase_name = phase.get("phase_name", "")
        phase_desc = phase.get("description", "")

        lines.append(f"# === {phase_name} ===")
        if phase_desc:
            lines.append(f"# {phase_desc}")
        lines.append("")

        for task in phase.get("tasks", []):
            task_id = task.get("task_id", "")
            task_desc = task.get("description", "")
            deps = task.get("dependencies", [])

            lines.append(f"# --- Task {task_id}: {task_desc} ---")
            if deps:
                lines.append(f"# Dependencies: {', '.join(deps)}")

            blocks = task.get("command_blocks", [])
            for block in blocks:
                block_type = block.get("type", "chain")
                comment = block.get("comment", "")
                command = block.get("command", "")

                if comment:
                    lines.append(f"# [{block_type}] {comment}")
                if command:
                    # Strip leading slash for .mcfunction format
                    cmd = command.lstrip("/")
                    lines.append(cmd)

            lines.append("")

    return "\n".join(lines)


def generate_single_command_mcfunction(command: str, explanation: str = "") -> str:
    """Generate a minimal .mcfunction for a single command."""
    lines: list[str] = []
    lines.append(f"# Generated by Minecraft BE AI Commander")
    lines.append(f"# Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    if explanation:
        lines.append(f"# {explanation}")
    lines.append("")
    lines.append(command.lstrip("/"))
    lines.append("")
    return "\n".join(lines)
